# config.yaml

# Network configuration
network:
  address: "localhost:50051"  # Network node address
  bootstrap_nodes:           # List of known nodes for initial connection
    - "node1.example.com:50051"
    - "node2.example.com:50051"
  heartbeat_interval: 30     # Seconds between heartbeats
  reconnect_delay: 60       # Seconds to wait before reconnection attempts

# Wallet configuration
wallet:
  address: "your_monero_address_here"
  rpc_url: "http://localhost:18082"  # Local wallet RPC
  rpc_username: "username"
  rpc_password: "password"
  min_payment: 0.01         # Minimum XMR for payout
  base_rate: 0.001         # Base XMR per GPU hour

# GPU configuration
gpu:
  max_temperature: 85       # Maximum GPU temperature (Celsius)
  max_power_usage: 250     # Maximum power usage (Watts)
  memory_buffer: 1024      # Memory buffer to maintain (MB)
  utilization_target: 95   # Target GPU utilization (%)

# Job preferences
job:
  frameworks:              # Supported ML frameworks
    - pytorch
  min_payment_rate: 0.0005  # Minimum XMR per hour
  max_job_duration: 86400   # Maximum job duration (seconds)
  preferred_job_types:     # Preferred types of jobs
    - training
    - fine-tuning

# Storage configuration
storage:
  work_dir: "./work"       # Directory for job working files
  max_storage: 100        # Maximum storage usage (GB)
  cleanup_threshold: 90    # Storage cleanup threshold (%)

# Logging configuration
logging:
  level: "INFO"
  file: "node.log"
  max_size: 100          # Maximum log file size (MB)
  backup_count: 5        # Number of backup log files

# Security configuration
security:
  enable_secure_enclave: false  # Use secure enclave if available
  enable_encryption: true      # Encrypt data in transit
  allowed_ips: []             # List of allowed IP addresses (empty for any)

# Performance configuration
performance:
  max_concurrent_jobs: 1    # Maximum concurrent jobs
  batch_size_limit: 32     # Maximum batch size
  prefetch_factor: 2       # Data loading prefetch factor
  enable_amp: true         # Enable automatic mixed precision

# Sybil Protection Settings
sybil_protection:
  # Minimum requirements
  min_stake: 0.1                  # Minimum XMR stake
  base_pow_difficulty: 5          # Base PoW difficulty
  min_reputation: 0.3             # Minimum reputation to participate
  
  # Geographic protection
  max_geo_cluster_size: 5         # Maximum nodes per geographic area
  proximity_threshold_km: 100     # Distance threshold for clustering
  max_nodes_per_subnet: 3         # Maximum nodes per subnet
  
  # Network protection
  max_connections_per_minute: 100 # Rate limiting
  min_peer_entropy: 2.0           # Minimum peer distribution entropy
  
  # Reputation settings
  reputation_decay: 0.99          # Daily reputation decay factor
  max_verification_history: 1000  # Maximum verification history entries
  
  # Response settings
  verification_invalidation_window: 86400  # 24 hours for invalidation
  max_response_history: 1000
  enable_stake_seizure: false     # Whether to seize stake on high severity
  
  # Metrics settings
  metrics:
    collection_interval: 300      # 5 minutes
    history_length: 288           # 24 hours at 5 min intervals